What does it mean when the army appears to be the only force able to contain the opponents of democracy, the armed Islamists? The former President of Pakistan Musharraf agrees to explore this apparent contradiction over dinner at his official residence, the Army House. As the discussion moves in and out of the different worlds in Pakistan, a complex tapestry emerges, revealing a society unique yet universal. The filmmaker talks to diverse individuals, from labourers to intellectuals, from street vendors to religious right wing political party members, and from journalists to industrialists. What is their idea of democracy in Pakistan? What is their idea of President Musharraf’s vision of a modern Pakistan? Dinner With the President questions the role a military leader can play in guiding a state towards modern democracy.What does it mean when the army appears to be the only force able to contain the opponents of democracy, the armed Islamists? The former President of Pakistan Musharraf agrees to explore this apparent contradiction over dinner at his official residence, the Army House. As the discussion moves in and out of the different worlds in Pakistan, a complex tapestry emerges, revealing a society unique yet universal. The filmmaker talks to diverse individuals, from labourers to intellectuals, from street vendors to religious right wing political party members, and from journalists to industrialists. What is their idea of democracy in Pakistan? What is their idea of President Musharraf’s vision of a modern Pakistan? Dinner With the President questions the role a military leader can play in guiding a state towards modern democracy.
# removing one line for test
Can democracy solve climate change?
Campaign! The Kawasaki Candidate
Kazuhiro Soda
In the fall of 2005, 40-year-old, self-employed Kazuhiko "Yama-san" Yamauchi's peaceful, humdrum life was turned upside-down. Japanese Prime Minister Junichiro Koizumi's Liberal Democratic Party (LDP) had suddenly chosen him as its official candidate to run for a vacant seat on the Kawasaki city council. Yama-san had zero experience in politics, no charisma, no supporters, no constituency, and no time to prepare for the impending election. The election was critical for the LDP. Adhering to the campaign tactic of "bowing to everybody, even to telephone poles," Yama-san visits local festivals, kindergarten sports events, senior gatherings, commuter train stations, and even bus stops to offer his hand to every one he sees. Can Yama-san win this heated race? Through its candid, cinema-verite style camerawork, this rare, detailed documentary of a Japanese election reveals the true nature of "democracy."

Can democracy solve climate change?
Campaign! The Kawasaki Candidate
Kazuhiro Soda
In the fall of 2005, 40-year-old, self-employed Kazuhiko "Yama-san" Yamauchi's peaceful, humdrum life was turned upside-down. Japanese Prime Minister Junichiro Koizumi's Liberal Democratic Party (LDP) had suddenly chosen him as its official candidate to run for a vacant seat on the Kawasaki city council. Yama-san had zero experience in politics, no charisma, no supporters, no constituency, and no time to prepare for the impending election. The election was critical for the LDP. Adhering to the campaign tactic of "bowing to everybody, even to telephone poles," Yama-san visits local festivals, kindergarten sports events, senior gatherings, commuter train stations, and even bus stops to offer his hand to every one he sees. Can Yama-san win this heated race? Through its candid, cinema-verite style camerawork, this rare, detailed documentary of a Japanese election reveals the true nature of "democracy." added one line for moving
 adding one line for created script sravanthi branch 
